baseURL = 'https://orphicsec.com/'
languageCode = 'en-us'
title = 'orphicsec'
theme = 'gruvbox'

pagination.pagerSize = 5

[params]
  author = { name = "mushyyy" }
  description = "Security Engineer & Lord of Order and Chaos"
  keywords = ["mushyyy", "security", "chaos", "order"]
  titlePrefix = ""
  titleSuffix = " | orphicsec.com"
  dateFormat = "2006-01-02"
  menuItemPrefix = "~/"
  postTruncateLength = 250
  hideGopher = false
  disqusAutoLoad = false
  disqusAutoLoadCount = false

[[menu.links]]
  name = "CV"
  identifier = "cv.pdf"
  url = "https://rawgit.com/bbrks/cv/master/cv.pdf"
  weight = 9999

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/bbrks_"
  weight = 1
[[menu.social]]
  name = "GitHub"
  url = "https://github.com/bbrks"
  weight = 10
[[menu.social]]
  name = "Keybase"
  url = "https://keybase.io/bbrks"
  weight = 30
[[menu.social]]
  name = "LinkedIn"
  url = "https://uk.linkedin.com/in/bbrks"
  weight = 100
