baseurl = "https://orphicsec.com"
enableEmoji = true
footnotereturnlinkcontents = "â†©"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
languageCode = "en-us"
theme = "hugo-classic"
title = "orphicsec"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
lineAnchors = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "modus-vivendi"
tabWidth = 4

[permalinks]
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "post"
url = "/post/"
weight = 1
[[menu.main]]
name = "about"
url = "/about/"
weight = 2
[[menu.main]]
name = "projects"
url = "/projects/"
weight = 3
[[menu.main]]
name = "ctf"
url = "/ctf/"
weight = 4

[params]
custom_css = ["css/theme-override.css"]
description = "Lord of Order and Chaos"
footer = "[Github](https://github.com/itsmushyyy) | [Keybase](https://keybase.io/goodroot)"
